services:
  postgres:
    container_name: container-pg
    image: postgres
    hostname: localhost
    # Map the container's port 5432 to the host's port 5432. If you have other PostgreSQL instances
    # running locally, adjust the host port (e.g., '5433:5432') to avoid conflicts.
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    container_name: container-pgadmin
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      # Similarly to the above comment. If you have other PostgreSQL instances running update this port
      - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    restart: unless-stopped

volumes:
  comments-section-data:
